### ISSUE TITLE
dlopen failed: cannot locate symbol "BIO_f_base64"

### ISSUE THREAD

**Issue by winneryong** [Adelbert1988/open_ssl_demo#1]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.security.open_ssl_ndk, PID: 10846
                  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "BIO_f_base64" referenced by "/data/app/com.security.open_ssl_ndk-1/lib/arm/libdefender.so"...
                      at java.lang.Runtime.loadLibrary(Runtime.java:372)
                      at java.lang.System.loadLibrary(System.java:1076)
                      at com.security.openssl.OpenSslUtil.<clinit>(OpenSslUtil.java:10)
                      at com.security.MainActivity.onCreate(MainActivity.java:45)
                      at android.app.Activity.performCreate(Activity.java:6303)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                      at android.app.ActivityThread.access$900(ActivityThread.java:153)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)

mac + 小米4
运行报错。

**Comment by winneryong** [comment]
sourceSets {
        main {
            jniLibs.srcDirs = ['libs', 'open-ssl-core/lib']
        }
    }
 这里加上'open-ssl-core/lib' 可以了

**Comment by Adelbert1988** [comment]
感谢解决这个问题，很久没看这个库了，以前没发现这个问题，最近在别的手机跑发现这个问题
